# Generated by Django 2.2 on 2022-05-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profliesfeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfliesFeedItem',
            new_name='ProfileFeedItem',
        ),
    ]
